{
 "title": "Web App",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "user", "label": "User", "query": "label_values(user)" },
   { "name": "method", "label": "Method", "query": "label_values(method)" },
   { "name": "endpoint", "label": "Endpoint", "query": "label_values(endpoint)" }
  ]
 },
 "panels": [
  {
   "title": "App info",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_info" }
   ]
  },
  {
   "title": "Total \"GET\"",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(app_requests_total{method=\"GET\", user=~\"$user\", endpoint=~\"$endpoint\"})"
    }
   ]
  },
  {
   "title": "Total \"POST\"",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(app_requests_total{method=\"POST\", user=~\"$user\", endpoint=~\"$endpoint\"})"
    }
   ]
  },
  {
   "title": "Total \"PATCH\"",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(app_requests_total{method=\"PATCH\", user=~\"$user\", endpoint=~\"$endpoint\"})"
    }
   ]
  },
  {
   "title": "Coupon creating time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(app_coupon_create_time_seconds_sum[1m])/rate(app_coupon_create_time_seconds_count[1m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "API calls",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "app_requests_total{user=~\"$user\", method=~\"$method\", endpoint=~\"$endpoint\"}"
    }
   ]
  },
  {
   "title": "Last activity",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "app_last_user_activity_time_seconds{user=~\"$user\"}*1000"
    }
   ]
  },
  {
   "title": "Coupon create last status",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": "sum(app_coupon_create_last_status{app_coupon_create_last_status=\"error\", user=~\"$user\"}) by (user)"
    }
   ]
  }
 ]
}